server:
#  tomcat.threads.max: 5
  port: ${PORT:2222}
  servlet:
    context-path: /backoffice

spring:
  application:
    name: containerized-main

management:
  endpoints:
    web:
      exposure:
        include: '*, prometheus'
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
logging:
  pattern:
    level: "trace_id=%X{traceId:-} span_id=%X{spanId:-} trace_flags=%X{trace_flags} %p"
  level:
    com.tanerdiler.microservice.main: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
---

spring:
  config:
    activate:
      on-profile: "platform"
  threads:
    virtual:
      enabled: false
---

spring:
  config:
    activate:
      on-profile: "virtual"
  threads:
    virtual:
      enabled: true

